all: es1 es1_v2 es2 es3 es4 es5 es6 es6_v2 es7 es7_lector es8

es1: es1.c
	gcc -o es1 es1.c

es1_v2: es1_v2.c
	gcc -o es1_v2 es1_v2.c

es2: es2.c
	gcc -o es2 es2.c

es3: es3.c
	gcc -o es3 es3.c

es4: es4.c
	gcc -o es4 es4.c

es5: es5.c
	gcc -o es5 es5.c

es6: es6.c
	gcc -o es6 es6.c

es6_v2: es6_v2.c
	gcc -o es6_v2 es6_v2.c

es7: es7.c
	gcc -o es7 es7.c

es7_lector: es7_lector.c
	gcc -o es7_lector es7_lector.c

es8: es8.c
	gcc -o es8 es8.c

clean:
	rm -r -f es1 es2 es3 es4 es5 es6 es7 es8
