all: myPS myPS_v0 myPS2 myPS3 parsExec

myPS: myPS.c
	gcc -o myPS myPS.c

myPS_v0: myPS_v0.c
	gcc -o myPS_v0 myPS_v0.c

myPS2: myPS2.c
	gcc -o myPS2 myPS2.c

myPS3: myPS3.c
	gcc -o myPS3 myPS3.c

parsExec: parsExec.c
	gcc -o parsExec parsExec.c

clean:
	rm -f myPS myPS_v0 myPS2 myPS3 parsExec
