all: procesos00 procesos01 procesos10 signals00 signals01 signals10 mem00

procesos00: procesos00.c
	gcc -o procesos00 procesos00.c

procesos01: procesos01.c
	gcc -o procesos01 procesos01.c

procesos10: procesos10.c
	gcc -o procesos10 procesos10.c

signals00: signals00.c
	gcc -o signals00 signals00.c

signals01: signals01.c
	gcc -o signals01 signals01.c

signals10: signals10.c
	gcc -o signals10 signals10.c

mem00: mem00.c
	gcc -o mem00 mem00.c

clean:
	rm procesos00 procesos01 procesos10 signals00 signals10 signals01 mem00